from typing import Any

class Db:
    def __init__(self, url: str = "http://127.0.0.1:4200") -> None: ...
    def create_db(self, name: str) -> None: ...
    def drop_db(self, name: str) -> None: ...
    def list_dbs(self) -> list[str]: ...
    def execute(self, db: str, sql: str) -> int: ...
    def query(self, sql: str) -> dict[str, Any]: ...
    def query_oltp(self, db: str, sql: str) -> dict[str, Any]: ...
    def list_tables(self, db: str) -> list[str]: ...
    def table_schema(self, db: str, table: str) -> dict[str, Any]: ...
    def health(self) -> bool: ...

def run_cli() -> None: ...
